# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8c4a0dd55c373d459512b40e624993661d13995c67dcb53ee76d632996f6745c1a288ae1da0758b5936905185ad413f8c31d2464984fe996fd8ae40e88e548

test:
  secret_key_base: 42232402cacc02016126ce50c60513fedbb9a18b354446b8e8206454f5723d052d2d8f4548c5b07a25c9d1077e0b7ceeffa1a0d24bb5cc11191be060abbcedb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
