Reference.create(URL: 'google.com', topic: 'sports', annotation: 'lots of shit about sports', datetime: '06/2/2016 01:19 AM')
Reference.create(URL: 'http://yahoo.com', topic: 'politics', annotation: 'lots of shit about politics', datetime: '06/2/2016 02:19 AM')
Reference.create(URL: 'http://wikipedia.com', topic: 'space', annotation: 'lots of shit about space', datetime: '06/12/2016 01:19 PM')
Reference.create(URL: 'http://wikipedia.com', topic: 'science', annotation: 'lots of shit about science', datetime: '06/13/2016 01:19 PM')
Reference.create(URL: 'http://reddit.com', topic: 'cats', annotation: 'lots of shit about cats', datetime: '06/13/2016 02:19 PM')
Reference.create(URL: 'http://reddit.com', topic: 'dogs', annotation: 'lots of shit about dog', datetime: '06/13/2016 01:20 PM')
Reference.create(URL: 'http://cnn.com', topic: 'news', annotation: 'lots of shit about shit', datetime: '06/13/2016 01:19 PM')
Reference.create(URL: 'http://gmail.com', topic: 'email', annotation: 'lots emails', datetime: '06/13/2016 01:19 PM')
Reference.create(URL: 'http://wikipedia.com', topic: 'checmistry', annotation: 'lots of science', datetime: '06/13/2016 01:19 PM')
Reference.create(URL: 'http://wikipedia.com', topic: 'physics', annotation: 'lots of physics', datetime: '06/13/2016 01:19 PM')
